# -*- coding: utf-8 -*-

[tradable]
spot= [
    "BTC",
    "ETH",
    #"XRP",
    #"SOL",     
       ]
strategy_labels= [#represert strategy
    "hedgingSpot",
    "futureSpread",
    "customLong",
    "customShort",
    #"marketMakerShort",
    #"marketMakerLong",
       ]

[paths]
root_dir = "/home/florian"