# -*- coding: utf-8 -*-

[[tradable]]
spot= [
    "BTC",
    "ETH",
    #"XRP",
    #"SOL",     
       ]
strategy_labels= [#represert strategy
    "hedgingSpot",
    "futureSpread",
    "customLong",
    "customShort",
    #"marketMakerShort",
    #"marketMakerLong",
       ]
       
[[strategies]]
strategy_label = "hedgingSpot"
is_active = true
contribute_to_hedging = true
cancellable = true
side = "sell"
take_profit_pct = 0
settlement_period = ["perpetual"]
weighted_factor = { minimum = 1, medium = 5, extreme=10, flash_crash= 20}
waiting_minute_before_cancel = 3 #basis?
halt_minute_before_reorder= 240
max_leverage= 1
delta_price_pct= 0.005


[[strategies]]
strategy_label = "futureSpread"
is_active = true
contribute_to_hedging = true
cancellable = false
side = "sell"
take_profit_pct = 0
settlement_period =  ["perpetual", "week"]
weighted_factor = { minimum = 1, medium = 5, extreme=10, flash_crash= 20}
waiting_minute_before_cancel = 3 #basis?
halt_minute_before_reorder= 240
max_leverage= 1
delta_price_pct= 0.005

[[strategies]]
strategy_label = "customLong"
is_active = false
contribute_to_hedging = true
cancellable = false
side = "sell"
take_profit_pct = 0
settlement_period = ["perpetual"]
weighted_factor = { minimum = 1, medium = 5, extreme=10, flash_crash= 20}
waiting_minute_before_cancel = 3 #basis?
halt_minute_before_reorder= 240
max_leverage= 1
delta_price_pct= 0.005

[[strategies]]
strategy_label = "customShort"
is_active = false
contribute_to_hedging = true
cancellable = false
side = "sell"
take_profit_pct = 0
settlement_period = ["perpetual"]
weighted_factor = { minimum = 1, medium = 5, extreme=10, flash_crash= 20}
waiting_minute_before_cancel = 3 #basis?
halt_minute_before_reorder= 240
max_leverage= 1
delta_price_pct= 0.005

[paths]
root_dir = "/home/florian"