# -*- coding: utf-8 -*-

[[tradable]]
spot= [
    "BTC",
    "ETH",
    #"XRP",
    #"SOL",     
       ]
strategy_labels= [#represert strategy
    "hedgingSpot",
    "futureSpread",
    "customLong",
    "customShort",
    #"marketMakerShort",
    #"marketMakerLong",
       ]
       
[[strategies]]
strategy_label = "hedgingSpot"
is_active = true
contribute_to_hedging = true

[[strategies]]
strategy_label = "futureSpread"
is_active = true
contribute_to_hedging = true

[[strategies]]
strategy_label = "customLong"
is_active = true
contribute_to_hedging = true

[[strategies]]
strategy_label = "customShort"
is_active = true
contribute_to_hedging = true


[paths]
root_dir = "/home/florian"