# -*- coding: utf-8 -*-

[tradable]
spot= [
    "BTC",
    "ETH",
    #"XRP",
    #"SOL",     
       ]
strategy_labels= [#represert strategy
    "hedgingSpot",
    "futureSpread",
    "customLong",
    "customShort",
    #"marketMakerShort",
    #"marketMakerLong",
       ]

[[strategies]]

[strategies.hedgingSpot] 
is_active = true
contribute_to_hedging = true

[[strategies.futureSpread]]  # nested array of tables
is_active = true
contribute_to_hedging = true

[[strategies.customLong]]
is_active = true
contribute_to_hedging = true

[[strategies.customShort]]
is_active = true
contribute_to_hedging = true


[paths]
root_dir = "/home/florian"