# -*- coding: utf-8 -*-

"""
For strategy with many derivatives name (a/b/c):
    good strategy name: 1) 'supplyDemandShort60A'/'supplyDemandShort60B'/supplyDemandShort60C'
    bad strategy name: 'supplyDemandShort60'
    why? because in sorting process, supplyDemandShort60 means all strategy 
        contains 'supplyDemandShort60', not exclusively 'supplyDemandShort60'
"""

equity_risked_pct_default = 1 / 100 / 4 #.25%

strategies = [
                {
                    "strategy": "every1hoursLong",
                    "instrument": ["PERPETUAL"],
                    "time_frame": 3600,
                    "side": "buy",
                    "entry_price": None,
                    "invalidation_entry_price": None,
                    "take_profit_usd": None,
                    "take_profit_pct": 1/100/4,
                    "quantity_discrete": None,
                    "cut_loss_usd": None,
                    "cut_loss_pct": None,
                    "averaging": None,
                    "halt_minute_before_reorder": 60,
                    "equity_risked_usd": None,
                    "equity_risked_pct": equity_risked_pct_default*4,
                },  {
                    "strategy": "every1hoursShort",
                    "instrument": ["PERPETUAL"],
                    "time_frame": 3600,
                    "side": "sell",
                    "entry_price": None,
                    "invalidation_entry_price": None,
                    "take_profit_usd": None,
                    "take_profit_pct": 1/100/4,
                    "quantity_discrete": None,
                    "cut_loss_usd": None,
                    "cut_loss_pct": None,
                    "averaging": None,
                    "halt_minute_before_reorder": 60,
                    "equity_risked_usd": None,
                    "equity_risked_pct": equity_risked_pct_default*4,
                }, {
                    "strategy": "every4hoursLong",
                    "instrument": ["PERPETUAL"],
                    "time_frame": 3600,
                    "side": "buy",
                    "entry_price": None,
                    "invalidation_entry_price": None,
                    "take_profit_usd": None,
                    "take_profit_pct": 1/100,
                    "quantity_discrete": None,
                    "cut_loss_usd": None,
                    "cut_loss_pct": None,
                    "averaging": None,
                    "halt_minute_before_reorder": 60*4,
                    "equity_risked_usd": None,
                    "equity_risked_pct": equity_risked_pct_default*8,
                },  {
                    "strategy": "every4hoursShort",
                    "instrument": ["PERPETUAL"],
                    "time_frame": 3600,
                    "side": "sell",
                    "entry_price": None,
                    "invalidation_entry_price": None,
                    "take_profit_usd": None,
                    "take_profit_pct": 1/100,
                    "quantity_discrete": None,
                    "cut_loss_usd": None,
                    "cut_loss_pct": None,
                    "averaging": None,
                    "halt_minute_before_reorder": 60*4,
                    "equity_risked_usd": None,
                    "equity_risked_pct": equity_risked_pct_default*8,
                }, 
                {
                    "strategy": "hedgingSpot",
                    "instrument": ["PERPETUAL"],
                    "time_frame": 900,
                    "side": "sell",
                    "entry_price": 1000,
                    "invalidation_entry_price": None,
                    "take_profit_usd": (1 / 100) / 15,
                    "take_profit_pct": (1 / 100)/2,
                    "quantity_discrete": 15,
                    "averaging": (5 / 100),
                    "cut_loss_usd": 15,
                    "cut_loss_pct": (3 / 100),
                    "halt_minute_before_reorder": 60 * 4,
                    "equity_risked_usd": 60,
                    "equity_risked_pct": (1 / 100),
                }
                
                ]


test = [{
                    "strategy": "supplyDemandShort60A",
                    "instrument": ["PERPETUAL"],
                    "time_frame": 3600,
                    "side": "sell",
                    "entry_price": 1880,
                    "invalidation_entry_price": 1920,
                    "take_profit_usd": 1840,
                    "take_profit_pct": 1 / 100,
                    "quantity_discrete": 15,
                    "cut_loss_usd": float(1950),
                    "cut_loss_pct": (1 / 100) / 2,
                    "averaging": 15,
                    "halt_minute_before_reorder": 60,
                    "equity_risked_usd": 60,
                    "equity_risked_pct": equity_risked_pct_default/2,
                }, 
                {
                    "strategy": "supplyDemandLongB",
                    "instrument": ["PERPETUAL"],
                    "time_frame": 3600,
                    "side": "buy",
                    "entry_price": 1860,
                    "invalidation_entry_price": 1830,
                    "take_profit_usd": float(1910),
                    "take_profit_pct": 1 / 100,
                    "quantity_discrete": 15,
                    "cut_loss_usd": 1783,
                    "cut_loss_pct": (1 / 100) / 5,
                    "averaging": 15,
                    "halt_minute_before_reorder": 60,
                    "equity_risked_usd": 60,
                    "equity_risked_pct": equity_risked_pct_default/2,
                },
                {
                    "strategy": "supplyDemandLongD",
                    "instrument": ["PERPETUAL"],
                    "time_frame": 3600,
                    "side": "buy",
                    "entry_price": 1872,
                    "invalidation_entry_price": 1860,
                    "take_profit_usd": float(1910),
                    "take_profit_pct": 1 / 100,
                    "quantity_discrete": 15,
                    "cut_loss_usd": 1850,
                    "cut_loss_pct": (1 / 100) / 5,
                    "averaging": 15,
                    "halt_minute_before_reorder": 60,
                    "equity_risked_usd": 60,
                    "equity_risked_pct": equity_risked_pct_default*2,
                }]
